In [1]:
import numpy as np
import pandas as pd

In [20]:
market = pd.read_csv("../data/farmersmarkets.csv", encoding='Latin-1')
market.head()

,FMID,MarketName,Website,Facebook,Twitter,Youtube,OtherMedia,street,city,County,...,Coffee,Beans,Fruits,Grains,Juices,Mushrooms,PetFood,Tofu,WildHarvested,updateTime
0,1018261,Caledonia Farmers Market Association - Danville,https://sites.google.com/site/caledoniafarmers...,https://www.facebook.com/Danville.VT.Farmers.M...,NaN,NaN,NaN,NaN,Danville,Caledonia,...,Y,Y,Y,N,N,Y,Y,N,N,6/20/2017 10:43:57 PM
1,1018318,Stearns Homestead Farmers' Market,http://www.StearnsHomestead.com,StearnsHomesteadFarmersMarket,NaN,NaN,NaN,6975 Ridge Road,Parma,Cuyahoga,...,N,N,Y,N,N,N,N,N,N,6/21/2017 5:15:01 PM
2,1009364,106 S. Main Street Farmers Market,http://thetownofsixmile.wordpress.com/,NaN,NaN,NaN,NaN,106 S. Main Street,Six Mile,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013
3,1010691,10th Steet Community Farmers Market,NaN,NaN,NaN,NaN,http://agrimissouri.com/mo-grown/grodetail.php...,10th Street and Poplar,Lamar,Barton,...,N,N,Y,N,N,N,N,N,N,10/28/2014 9:49:46 AM
4,1002454,112st Madison Avenue,NaN,NaN,NaN,NaN,NaN,112th Madison Avenue,New York,New York,...,N,N,N,N,N,N,N,N,N,3/1/2012 10:38:22 AM

In [11]:
# Check the shape of data
market.shape

(8687, 59)

In [12]:
# See columns names
market.columns

Index(['FMID', 'MarketName', 'Website', 'Facebook', 'Twitter', 'Youtube',
       'OtherMedia', 'street', 'city', 'County', 'State', 'zip', 'Season1Date',
       'Season1Time', 'Season2Date', 'Season2Time', 'Season3Date',
       'Season3Time', 'Season4Date', 'Season4Time', 'x', 'y', 'Location',
       'Credit', 'WIC', 'WICcash', 'SFMNP', 'SNAP', 'Organic', 'Bakedgoods',
       'Cheese', 'Crafts', 'Flowers', 'Eggs', 'Seafood', 'Herbs', 'Vegetables',
       'Honey', 'Jams', 'Maple', 'Meat', 'Nursery', 'Nuts', 'Plants',
       'Poultry', 'Prepared', 'Soap', 'Trees', 'Wine', 'Coffee', 'Beans',
       'Fruits', 'Grains', 'Juices', 'Mushrooms', 'PetFood', 'Tofu',
       'WildHarvested', 'updateTime'],
      dtype='object')

In [13]:
# media data such as Facebook, Twitter, Youtube are missing largely, and Season2~4Date and Time data are mostly null.
market.isnull().sum()

FMID                0
MarketName          0
Website          3475
Facebook         4758
Twitter          7679
Youtube          8516
OtherMedia       7967
street            290
city               40
County            515
State               0
zip               947
Season1Date      3208
Season1Time      3050
Season2Date      8238
Season2Time      8250
Season3Date      8606
Season3Time      8610
Season4Date      8681
Season4Time      8679
x                  29
y                  31
Location         5956
Credit              0
WIC                 0
WICcash             0
SFMNP               0
SNAP                0
Organic             2
Bakedgoods       2933
Cheese           2933
Crafts           2933
Flowers          2933
Eggs             2933
Seafood          2933
Herbs            2933
Vegetables       2933
Honey            2933
Jams             2933
Maple            2933
Meat             2933
Nursery          2933
Nuts             2933
Plants           2933
Poultry          2933
Prepared         2933
Soap             2933
Trees            2933
Wine             2933
Coffee           2933
Beans            2933
Fruits           2933
Grains           2933
Juices           2933
Mushrooms        2933
PetFood          2933
Tofu             2933
WildHarvested    2931
updateTime          2
dtype: int64

In [19]:
# See Season1Date format
# Some data are missing end date values and some data are missing year values
market.loc[:20,"Season1Date"]

0     06/14/2017 to 08/30/2017
1     06/24/2017 to 09/30/2017
2                          NaN
3     04/02/2014 to 11/30/2014
4             July to November
5     05/05/2015 to 10/27/2015
6     06/10/2014 to 11/25/2014
7     05/16/2014 to 10/17/2014
8     05/03/2014 to 11/22/2014
9     04/09/2016 to 11/19/2016
10    06/29/2017 to 11/22/2017
11           June to September
12              06/08/2017 to
13    06/01/2015 to 11/15/2015
14    06/07/2014 to 09/27/2014
15    05/20/2017 to 09/30/2017
16    09/03/2016 to 06/24/2017
17    01/01/2016 to 12/31/2016
18    06/05/2015 to 10/30/2015
19    06/01/2015 to 11/01/2015
20    06/25/2016 to 11/05/2016
Name: Season1Date, dtype: object

In [36]:
# Check updateTime format
# 'MM/DD/YYYY Time' format are general, but some are 'Month DD Year Time' format.
market.loc[50:70,"updateTime"]

50     6/28/2016 1:05:51 AM
51     9/29/2014 1:37:38 PM
52      5/3/2012 5:01:00 PM
53     5/6/2014 10:28:06 PM
54      4/8/2014 1:54:22 PM
55    7/23/2011 11:54:21 PM
56      4/5/2014 7:27:30 PM
57     7/11/2013 1:41:58 PM
58     5/7/2012 10:47:54 AM
59      May 26 2010 11:24PM
60                     2009
61                     2009
62     3/2/2016 10:20:28 AM
63    7/24/2013 10:36:51 AM
64    3/14/2014 10:44:35 AM
65                     2009
66     6/30/2016 1:50:15 PM
67      6/5/2014 2:51:15 PM
68                     2013
69                     2009
70                     2011
Name: updateTime, dtype: object

In [33]:
# Check city data
# Some data are similar, which should be clustered together by clustering or trimming
list(pd.unique(market.loc[:100, "city"]))

['Danville',
 'Parma ',
 'Six Mile',
 'Lamar ',
 'New York',
 'Nashville',
 'Wilmington',
 'Washington',
 'Washington ',
 'New York ',
 'Minneapolis',
 'Richmond ',
 'Philadelphia',
 'Scottsbluff',
 'Charleston ',
 'Chiefland',
 'Woodinville',
 'Topeka',
 'Highlands',
 'North Logan',
 'Amherst',
 'Dayton',
 'Morris',
 'Rosemary Beach',
 'Ewing',
 'Baltimore',
 'Indianapolis',
 'Sparks',
 'Carson City',
 'Rochester',
 'Larimer',
 'Chicago ',
 'Tempe ',
 'Dothan',
 'Cedar Rapids',
 'Salina',
 'SALT LAKE CITY',
 'Boynton Beach ',
 'Brunswick',
 'Tallahassee ',
 'Anderson',
 'Annapolis',
 'Abbeville ',
 'Abbeville',
 'Abbotsford',
 'Aberdeen',
 'Abilene',
 'Abingdon ',
 'Abington',
 'Clarks Summit',
 'Abita Springs',
 'Albququerque',
 'Mount Bethe',
 'Town Hill',
 'Opelousas',
 'Rome',
 'Birch Tree',
 'Loxahatchee',
 'Acton',
 'Acushnet',
 'Acworth',
 'Ada',
 'Columbia',
 'Adairsville',
 'Gettysburg borough',
 'Gettysburg',
 'Adams',
 'Washington, DC',
 'Kealakekua',
 'Brooklyn',
 'Addison',
 'Adel',
 'Victorville',
 'Adrian ',
 'Concord',
 'Berlin',
 'Memphis',
 'Gilbert',
 'Phoenix',
 'Aiken',
 'Brooksville',
 'Pahoa',
 'Baker']

In [31]:
# Check website format
market.loc[:20,"Website"]

0     https://sites.google.com/site/caledoniafarmers...
1                       http://www.StearnsHomestead.com
2                http://thetownofsixmile.wordpress.com/
3                                                   NaN
4                                                   NaN
5                   http://www.12southfarmersmarket.com
6               http://www.125thStreetFarmersMarket.com
7                                                   NaN
8                                                   NaN
9                                                   NaN
10    https://www.grownyc.org/greenmarket/manhattan/...
11                      http://www.iatp.org/minimarkets
12                                http://enrichmond.org
13    http://thefoodtrust.org/farmers-markets/market...
14                                                  NaN
15                                                  NaN
16                                                  NaN
17                                   http://21acres.org
18                                                  NaN
19    http://thefoodtrust.org/farmers-markets/market...
20                           http://www.highlandsnj.com
Name: Website, dtype: object

In [32]:
# Check twitter format
# While some starts with "https~", some starts with @
market.loc[:20,"Twitter"]

0                                     NaN
1                                     NaN
2                                     NaN
3                                     NaN
4                                     NaN
5                         @12southfrmsmkt
6     https://twitter.com/FarmMarket125th
7                                     NaN
8       https://twitter.com/14UFarmersMkt
9                                 14KenFM
10                                    NaN
11                                    NaN
12                                    NaN
13                                    NaN
14                                    NaN
15                                    NaN
16                                    NaN
17                               @21acres
18                                    NaN
19                                    NaN
20                                    NaN
Name: Twitter, dtype: object